name: Collect Game Data

on:
  schedule:
    - cron: "*/2 * * * *"  # runs every 2 minutes
  workflow_dispatch:      # allows manual run

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Collector Script
        run: |
          python collector.py

      - name: Commit Updated Data
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add game_data.json
          git commit -m "Update game data [bot]" || echo "No changes"
          git push
